### ISSUE TITLE
Проблемы с запуском на Mac

### ISSUE THREAD

**Issue by ketsu8** [IgorTimofeev/OpenComputersVM#3]
Попробовал запустить на маке последнюю версию OpenComputersVM, и при запуске Java не может загрузить главный класс.

```sh
$ java -jar OpenComputersVM.jar 
Error: Could not find or load main class vm.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

Гифки:

![](http://g.recordit.co/SsOtYkqzEj.gif)
![](http://g.recordit.co/tx2mw8x1R4.gif)

Вероятно, проблемы на моей стороне. В Java не силен 🙂

**Comment by IgorTimofeev** [comment]
Мяу, тоже не разбираюсь в этом. Возможно, стоит жава < 8 версии. А вообще приложуха без проблем должна запускаться двойным кликом:

![2019-02-08 8 05 51](https://user-images.githubusercontent.com/11760002/52459814-614cbe00-2b78-11e9-92eb-3c83ad537069.png)

При запуске через java -jar нужно прописывать мейн класс, что у тебя и требует терминал. А поскольку это жабаФх-приложуха, мейн класс прописывается через пизду и костыли))00

**Comment by ketsu8** [comment]
Понятно в общем. Java в репертуаре.
