### ISSUE TITLE
Можно ли завезти data card?

### ISSUE THREAD

**Issue by IS2511** [IgorTimofeev/OpenComputersVM#4]
Улучшения так сказать. И можно ли как-то другие компоненты добавлять? Все запущенные компы в одной локалке (на 1 блоке)?

**Comment by IgorTimofeev** [comment]
Оч лень. Я с криптографией никогда не работал, а ради эмулятора, которым я не пользуюсь, изучать все эти эллиптические алгоритмы, кей-пары, хуё-моё... лень.

Насчет одной локалки в блоке не понял. Все запущенные компы - это самостоятельные виртуалки со своими адресами компонентов. Сообщения между компами по модемам (wireless тольк) поддерживаются

**Comment by IS2511** [comment]
Тогда немного абстрактный вопрос, можно ли построить окружение OC чисто на луа?

**Comment by IgorTimofeev** [comment]
@IS2511 Ну да, чому нет? Тут вон на явке построено - можно и на луа. Но тебе все равно потребуется какой-нибудь пиздатый фреймворк для отрисовки графена, для обработки ивентов и прочего говна. Какой-нибудь [Love](https://love2d.org/), например

Хотя скорость не шибко жирной будет, но для эмуля более чем достаточной

**Comment by IS2511** [comment]
Надо будет посидеть подумать
