### ISSUE TITLE
GPL Licence contains a typo

### ISSUE THREAD

**Issue by FrostyPenguin** [IgorTimofeev/OpenComputersVM#6]
Hey, first of thanks for making this amazing program. However, I noticed that your version of the GPL contains the line (line 142)

> the work, and the source code for shared **vm.**libraries and dynamically

Is this a typo? If so, I'd overwrite the LICENCE file with the original GPL (fetched from https://www.gnu.org/licenses/gpl.txt).
In fact, I've created a small pull request for this (#5).

On the other hand, given that this program is a VM this might be intentional. In that case, please ignore this issue and PR.

**Comment by IgorTimofeev** [comment]
nah, i just don't care about this shit, license file was autogenerated
